import "./globals.scss";
import { LoadingProvider } from "@/contexts/loading";
import { ToastContainer } from "react-toastify";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<LoadingProvider>
				<body>
					{children}
					<ToastContainer
						position="top-center"
						autoClose={3000}
						hideProgressBar={true}
						newestOnTop={false}
						closeOnClick
						rtl={false}
						pauseOnFocusLoss
						theme="light"
					/>
				</body>
			</LoadingProvider>
		</html>
	);
}
